name: activite1
description: A sample Flutter project.
version: 1.0.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/magazineInfo.jpg
    - assets/images/presse.jpg
    - assets/images/design.jpg